id: P002973
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG23520
  title: རི་མོའི་འཇུག་སྒོ།
  author: ''
  volumes:
    99347d8720444a95a7b1e62227721958:
      image_group_id: I1KG23573
      title: ''
      volume_number: 1
      total_pages: 154
      base_file: v001.txt
