id: I84294167
legacy_id: P002973
ocr_import_info:
  bdrc_scan_id: W1KG23520
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T13:52:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:31:57.017779+00:00'
last_modified: 2022-08-31 21:32:04.314063
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG23520
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG23520
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རི་མོའི་འཇུག་སྒོ
statistics:
  ocr_word_mean_confidence_index: 0.6810976152607802
  ocr_word_median_confidence_index: 0.9300000071525574
quality: null
bases:
  I1KG23573:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG23573
      total_pages: 154
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG23573.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.6810976152607802
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
